#!/bin/bash

# Hook script to check for the correct format of the commit message.

# Format regex.
format="\A(\[((build|ci|docs|src|test|merge|etc)\] (Add|Integrate|Remove|Amend|Merge .* into|Fix|Refractor|Update|Revise|Modify) .*[^\.]\n\n[A-Z](.|\n)+\.\n(\n(Closes #[0-9]+((, #[0-9]+)* and #[0-9]+)?\n)?(References #[0-9]+((, #[0-9]+)* and #[0-9]+)?\n)?)?)|etc\] Initial commit\n)(#.*\n)*\n*\z"

# Parse the commit message.
grep -Pqze "$format" $1

if [ $? -ne 0 ]; then
  # Handle an invalid commit message.
  echo "The commit message does not follow the convention. You may have a look at the commit message template at .gittemplates/commit.txt."
  # Do not allow the commit to continue.
  exit 1
fi

# Allow the commit to continue.
exit 0
