#!/bin/bash

# Hook script to check for the correct format of to be pushed commit messages.

# Iterate over all to be pushed commits.
while read -r change; do
  # Get the current hash of the commit.
  readarray -d ' ' -t hashes<<<"$change"
  current_hash=${hashes[1]}

  # Format regex.
  format="\A(\[((build|ci|docs|src|test|merge|etc)\] (Add|Integrate|Remove|Amend|Merge .* into|Fix|Refractor|Update|Revise|Modify) .*[^\.]\n\n[A-Z](.|\n)+\.\n(\n(Closes #[0-9]+((, #[0-9]+)* and #[0-9]+)?\n)?(References #[0-9]+((, #[0-9]+)* and #[0-9]+)?\n)?)?)|etc\] Initial commit\n)(#.*\n)*\n*\z"

  # Parse the commit message.
  git log --format=%B -n 1 $current_hash | grep -Pqze "$format"

  if [ $? -ne 0 ]; then
    # Handle an invalid commit message.
    echo "The commit message for" $current_hash "does not follow the convention. You may have a look at the commit message template at .gittemplates/commit.txt."
    # Do not allow the push to continue.
    exit 1
  fi
done

# Allow the commit to continue.
exit 0
